name: fiil_up_app
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^3.3.0
  firebase_storage: ^12.1.2
  firebase_auth: ^5.1.3
  cloud_firestore: ^5.2.0
  circle_nav_bar: ^2.0.1+1
  geolocator: ^12.0.0
  permission_handler: ^11.3.1
  google_fonts: ^6.2.1
  image_picker: ^1.1.2
  cached_network_image: ^3.4.0
  flutter_map: ^7.0.2
  latlong2: ^0.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:


  uses-material-design: true


  assets:
     - assets/images/fm.png

